version: '3.8'

services:
  rag-server:
    image: ${RAG_SERVER_IMAGE}
    ports:
      - 5000:5000
    depends_on:
      - vector-db-weaviate-service
    environment:
      GEMINI_FLASH_API_KEY: ${GEMINI_FLASH_API_KEY}
      WEAVIATE_DB_HOST: vector-db-weaviate-service:5555
    networks:
      - rag-net
  vector-db-weaviate-service:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '5555'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.4
    ports:
      - 5555:5555
      - 50051:50051
    volumes:
      - weaviate_db_data:/var/lib/weaviate
    networks:
      - rag-net
    restart: on-failure:0
    logging:
      driver: none
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_db_data:
networks:
  rag-net: